Balance And/Or types when forming lubs and glbs
scala/scala3 pull request #12928
Opened 2021-06-24 15:03 UTC by odersky

Fixes #12915

2021-06-24 15:10 UTC, odersky commented
test performance please

2021-06-25 14:36 UTC, bishabosha commented
I tested this by replicating #7034, it resolves the stack overflow in subtyping (which would happen at about 500 unique string arguments on master on my machine).

I can now compile and infer the type argument for an IArray of 4750 unique strings.

On my machine it takes about 3x as long to compile the given file (5 iterations of invoking `scalac` sbt task) with inference vs explicit type argument to IArray. You can see the file by expanding the details below.

at about 4760 unique string elements (on my machine) it now exposes another stack overflow, which is `recur` in `mapWithIndexConserve`, called by `FunProto.typedArgs`

Here is the test file of strings:
<details>

```scala
// explicit typing (IArray[String](...)) = 0m 21.82s for 5 iterations
// implicit typing (IArray(...))         = 1m 07.72s for 5 iterations
val names = IArray(
  "Aaron",
  "Abdiel",
  "Abdul",
  "Abdullah",
  "Abe",
  "Abel",
  "Abner",
  "Abraham",
  "Abram",
  "Adalberto",
  "Adam",
  "Adan",
  "Addison",
  "Adelard",
  "Adelbert",
  "Aditya",
  "Adolf",
  "Adolfo",
  "Adolph",
  "Adolphus",
  "Adonis",
  "Adrain",
  "Adrian",
  "Adrien",
  "Agustin",
  "Ahmad",
  "Ahmed",
  "Aidan",
  "Aiden",
  "Akeem",
  "Al",
  "Alan",
  "Albert",
  "Alberto",
  "Albin",
  "Alden",
  "Aldo",
  "Alec",
  "Alejandro",
  "Alek",
  "Alessandro",
  "Alex",
  "Alexander",
  "Alexandre",
  "Alexandrer",
  "Alexandro",
  "Alexis",
  "Alf",
  "Alfonso",
  "Alfonzo",
  "Alford",
  "Alfred",
  "Alfredo",
  "Ali",
  "Allan",
  "Allen",
  "Allie",
  "Allison",
  "Allyn",
  "Alma",
  "Alois",
  "Alonso",
  "Alonza",
  "Alonzo",
  "Aloysius",
  "Alpha",
  "Alphonse",
  "Alphonso",
  "Alton",
  "Alva",
  "Alvah",
  "Alvaro",
  "Alvie",
  "Alvin",
  "Alvis",
  "Amado",
  "Amador",
  "Amanda",
  "Amari",
  "Ambrose",
  "Americo",
  "Amir",
  "Amos",
  "Amy",
  "Anastacio",
  "Anderson",
  "Andra",
  "Andre",
  "Andrea",
  "Andreas",
  "Andres",
  "Andrew",
  "Andy",
  "Angel",
  "Angela",
  "Angelo",
  "Angus",
  "Anibal",
  "Anna",
  "Ansel",
  "Anselmo",
  "Anthony",
  "Antione",
  "Antoine",
  "Anton",
  "Antone",
  "Antonia",
  "Antonio",
  "Antony",
  "Antwan",
  "Antwon",
  "Arcadio",
  "Arch",
  "Archibald",
  "Archie",
  "Ardell",
  "Arden",
  "Ari",
  "Aric",
  "Ariel",
  "Arlan",
  "Arlen",
  "Arley",
  "Arlie",
  "Arlin",
  "Arlis",
  "Arlo",
  "Arman",
  "Armand",
  "Armando",
  "Armani",
  "Armond",
  "Arnaldo",
  "Arne",
  "Arno",
  "Arnold",
  "Arnoldo",
  "Arnulfo",
  "Aron",
  "Arron",
  "Art",
  "Arther",
  "Arthur",
  "Artie",
  "Artis",
  "Arturo",
  "Arvel",
  "Arvid",
  "Arvil",
  "Arvin",
  "Asa",
  "Asher",
  "Ashley",
  "Ashton",
  "Aubrey",
  "Audie",
  "Audrey",
  "August",
  "Augustine",
  "Augustus",
  "Aurelio",
  "Austen",
  "Austin",
  "Auston",
  "Austyn",
  "Avery",
  "Axel",
  "Ayden",
  "Bailey",
  "Barbara",
  "Barney",
  "Baron",
  "Barrett",
  "Barron",
  "Barry",
  "Bart",
  "Bartholome",
  "Barton",
  "Basil",
  "Beau",
  "Ben",
  "Benedict",
  "Benito",
  "Benjamin",
  "Bennett",
  "Bennie",
  "Benny",
  "Benton",
  "Bernard",
  "Bernardo",
  "Bernhard",
  "Bernice",
  "Bernie",
  "Berry",
  "Bert",
  "Berton",
  "Bertram",
  "Bertrand",
  "Beryl",
  "Betty",
  "Beverly",
  "Bienvenido",
  "Bill",
  "Billie",
  "Billy",
  "Bishop",
  "Blaine",
  "Blair",
  "Blaise",
  "Blake",
  "Blane",
  "Bo",
  "Bob",
  "Bobbie",
  "Bobby",
  "Bonnie",
  "Booker",
  "Boris",
  "Boyce",
  "Boyd",
  "Brad",
  "Braden",
  "Bradford",
  "Bradley",
  "Bradly",
  "Brady",
  "Braeden",
  "Braedon",
  "Braiden",
  "Brain",
  "Brandan",
  "Branden",
  "Brandon",
  "Brandt",
  "Brandy",
  "Brandyn",
  "Brannon",
  "Branson",
  "Brant",
  "Braulio",
  "Braxton",
  "Brayan",
  "Brayden",
  "Braydon",
  "Brendan",
  "Brenden",
  "Brendon",
  "Brennan",
  "Brennen",
  "Brennon",
  "Brent",
  "Brenton",
  "Bret",
  "Brett",
  "Brian",
  "Brice",
  "Bridger",
  "Brien",
  "Britt",
  "Brock",
  "Broderick",
  "Brody",
  "Bronson",
  "Brook",
  "Brooks",
  "Brown",
  "Bruce",
  "Bruno",
  "Bryan",
  "Bryant",
  "Bryce",
  "Brycen",
  "Bryon",
  "Bryson",
  "Buck",
  "Bud",
  "Buddie",
  "Buddy",
  "Buford",
  "Burdette",
  "Burl",
  "Burley",
  "Burnell",
  "Burt",
  "Burton",
  "Buster",
  "Butch",
  "Byron",
  "Cade",
  "Caden",
  "Caesar",
  "Cale",
  "Caleb",
  "Calvin",
  "Camden",
  "Cameron",
  "Camren",
  "Camron",
  "Candelario",
  "Candido",
  "Carey",
  "Carl",
  "Carleton",
  "Carlo",
  "Carlos",
  "Carlton",
  "Carlyle",
  "Carmelo",
  "Carmen",
  "Carmine",
  "Carnell",
  "Carol",
  "Carolyn",
  "Carrol",
  "Carroll",
  "Carson",
  "Carter",
  "Cary",
  "Casey",
  "Casimer",
  "Casimir",
  "Casper",
  "Cassidy",
  "Cayden",
  "Cecil",
  "Cecilio",
  "Cedric",
  "Cedrick",
  "Celestino",
  "Cesar",
  "Chad",
  "Chadd",
  "Chadrick",
  "Chadwick",
  "Chaim",
  "Chance",
  "Chandler",
  "Charles",
  "Charley",
  "Charlie",
  "Chas",
  "Chase",
  "Chauncey",
  "Chaz",
  "Chesley",
  "Chester",
  "Chet",
  "Chip",
  "Chris",
  "Christ",
  "Christian",
  "Christina",
  "Christion",
  "Christop",
  "Christoper",
  "Christophe",
  "Christopher",
  "Chuck",
  "Cicero",
  "Clair",
  "Claire",
  "Clarance",
  "Clare",
  "Clarence",
  "Clark",
  "Claud",
  "Claude",
  "Claudie",
  "Claudio",
  "Clay",
  "Clayton",
  "Clem",
  "Clemens",
  "Clement",
  "Cleo",
  "Cleon",
  "Cletus",
  "Cleve",
  "Cleveland",
  "Cliff",
  "Clifford",
  "Clifton",
  "Clint",
  "Clinton",
  "Clovis",
  "Cloyd",
  "Clyde",
  "Coby",
  "Codey",
  "Codie",
  "Cody",
  "Colby",
  "Cole",
  "Coleman",
  "Colin",
  "Collin",
  "Colt",
  "Colten",
  "Colton",
  "Columbus",
  "Conner",
  "Connie",
  "Connor",
  "Conor",
  "Conrad",
  "Constantin",
  "Cooper",
  "Corbin",
  "Cordell",
  "Corey",
  "Cornelius",
  "Cornell",
  "Cortez",
  "Cortney",
  "Cory",
  "Coty",
  "Courtney",
  "Coy",
  "Craig",
  "Crawford",
  "Cris",
  "Cristian",
  "Cristobal",
  "Cristopher",
  "Cruz",
  "Cullen",
  "Curt",
  "Curtis",
  "Curtiss",
  "Cyril",
  "Cyrus",
  "Dakota",
  "Dakotah",
  "Dale",
  "Dallas",
  "Dallin",
  "Dalton",
  "Dameon",
  "Damian",
  "Damien",
  "Damion",
  "Damon",
  "Dan",
  "Dana",
  "Dandre",
  "Dane",
  "Dangelo",
  "Danial",
  "Daniel",
  "Dannie",
  "Danny",
  "Dante",
  "Daquan",
  "Darby",
  "Darell",
  "Daren",
  "Darian",
  "Darien",
  "Darin",
  "Dario",
  "Darion",
  "Darius",
  "Darnell",
  "Darold",
  "Daron",
  "Darrel",
  "Darrell",
  "Darren",
  "Darrian",
  "Darrick",
  "Darrien",
  "Darrin",
  "Darrion",
  "Darrius",
  "Darron",
  "Darryl",
  "Darwin",
  "Daryl",
  "Daryle",
  "Dashawn",
  "Dave",
  "Davey",
  "David",
  "Davie",
  "Davin",
  "Davion",
  "Davis",
  "Davon",
  "Davonte",
  "Davy",
  "Dawson",
  "Dax",
  "Dayton",
  "Dean",
  "Deandre",
  "Deane",
  "Deangelo",
  "Deborah",
  "Debra",
  "Declan",
  "Dedric",
  "Dedrick",
  "Dee",
  "Deion",
  "Dejuan",
  "Del",
  "Delano",
  "Delbert",
  "Dell",
  "Delmar",
  "Delmas",
  "Delmer",
  "Delton",
  "Delvin",
  "Demarco",
  "Demarcus",
  "Demario",
  "Demetris",
  "Demetrius",
  "Demond",
  "Dempsey",
  "Denis",
  "Dennie",
  "Dennis",
  "Denny",
  "Denton",
  "Denver",
  "Denzel",
  "Denzil",
  "Deon",
  "Deondre",
  "Deontae",
  "Deonte",
  "Dequan",
  "Dereck",
  "Derek",
  "Deric",
  "Derick",
  "Derik",
  "Deron",
  "Derrell",
  "Derrick",
  "Derwin",
  "Deshaun",
  "Deshawn",
  "Desmond",
  "Destin",
  "Devan",
  "Devante",
  "Deven",
  "Devin",
  "Devon",
  "Devonta",
  "Devontae",
  "Devonte",
  "Devyn",
  "Dewayne",
  "Dewey",
  "Dewitt",
  "Dexter",
  "Diamond",
  "Dick",
  "Dickie",
  "Diego",
  "Dillan",
  "Dillard",
  "Dillion",
  "Dillon",
  "Dimitri",
  "Dino",
  "Dion",
  "Dionisio",
  "Dionte",
  "Dirk",
  "Dock",
  "Dolores",
  "Domenic",
  "Domenick",
  "Domenico",
  "Domingo",
  "Dominic",
  "Dominick",
  "Dominik",
  "Dominique",
  "Dominque",
  "Don",
  "Donal",
  "Donald",
  "Donato",
  "Donavan",
  "Donavon",
  "Donell",
  "Donn",
  "Donna",
  "Donnell",
  "Donnie",
  "Donny",
  "Donovan",
  "Donta",
  "Donta [...]

2021-06-28 12:14 UTC, bishabosha approved these changes
for the balancing change it looks good, I guess a new issue can be opened for `mapWithIndexConserve` not being stack safe

2021-06-28 13:55 UTC, merged

2023-04-21 20:04 UTC, Sdssourcing commented
#

2023-12-17 03:07 UTC, Claudioschiro requested changes
Idioma

2024-01-08 01:54 UTC, mistressxalexis reviewed
Lg