scaladoc should take -Werror/-Xfatal-warnings into account
scala/scala3 pull request #17023
Opened 2023-02-27 18:20 UTC by mkurz

Alternative to #17022

2023-05-09 19:03 UTC, som-snytt commented
Scaladoc settings already uses `AllScalaSettings`. I must be missing something. That's what I intended on the other PR.

https://github.com/lampepfl/dotty/blob/main/scaladoc/src/dotty/tools/scaladoc/ScaladocSettings.scala#L6

2023-12-08 00:23 UTC, som-snytt commented
The relevant filtering is at https://github.com/lampepfl/dotty/blame/main/scaladoc/src/dotty/tools/scaladoc/Scaladoc.scala#L123

where only common settings are retained.

I tried it out locally. I see the use case is that Scaladoc tool emits warnings.
```
$ ~/projects/dotty/bin/scaladoc -d /tmp/sandbox -Werror S.tasty
-- Error: s.scala:7:6 --------------------------------------------------------------------------------------------------
7 |class S {
  |      ^
  |      No DRI found for query: some
```

`-Wconf` could also be relocated to common. I'll try it out, too, albeit I put them after `silentWarnings`.

Incremental compilation breaks with this edit, alas.

2023-12-08 00:24 UTC, som-snytt approved these changes
This looks good and could even move Wconf.

2023-12-08 00:25 UTC, som-snytt requested changes
Must rerun CI anyway, and add Wconf definitely.

2023-12-08 01:00 UTC, som-snytt commented
scaladoc/build says
```
Problem parsing scaladoc/src/dotty/tools/scaladoc/tasty/ClassLikeSupport.scala:[0..29..29489], documentation may not be generated.
Problem parsing scaladoc/src/dotty/tools/scaladoc/tasty/InkuireSupport.scala:[0..29..16233], documentation may not be generated.
Problem parsing scaladoc/src/dotty/tools/scaladoc/tasty/PackageSupport.scala:[0..20..517], documentation may not be generated.
Error:  -- Error: scaladoc/src/dotty/tools/scaladoc/tasty/comments/wiki/Entities.scala:10:17 
Error:  10 |final case class Body(blocks: Seq[Block]) {
Error:     |                 ^
Error:     |       No DRI found for query: scala.tools.nsc.doc.model.comment.Summary
Error:  -- Error: docs/_docs/index.md --------------------------------------------------
Error:  /home/runner/work/dotty/dotty/./docs/_docs/index.md: Unable to resolve link 'docs/reference/index.html'
Error:  -- Error: docs/_docs/reference/overview.md -------------------------------------
Error:  /home/runner/work/dotty/dotty/./docs/_docs/reference/overview.md: Unable to resolve link 'new-types/intersection-types.md'
Error:  -- Error: docs/_docs/reference/overview.md -------------------------------------
Error:  /home/runner/work/dotty/dotty/./docs/_docs/reference/overview.md: Unable to resolve link 'new-types/union-types.md'
Error:  -- Error: docs/_docs/reference/overview.md -------------------------------------
```
I'll attempt to follow up.

2024-08-09 13:07 UTC, dabrowski-adam commented
This would be very helpful to work around https://github.com/scala/scala3/issues/20028 In a project that I work on, we had to disable treating warnings as errors because  `No DRI found for query: Enum` caused `sbt publishLocal` to fail.

2025-01-09 12:28 UTC, KacperFKorban commented
@dabrowski-adam I think that there is a specific scaladoc setting for disabling these warnings - `-no-link-warnings`.

2026-02-16 10:23 UTC, tgodzik commented
@som-snytt @mkurz We're looking through older PRs and hoping to reduce their number. What is the status here? What needs to be done still?

Or maybe we can close it now and continue in a new PR?

2026-02-16 22:28 UTC, closed without merging

2026-02-16 22:28 UTC, som-snytt commented
> hoping to reduce their number

This PR will always be 17023. It's not possible to reduce its number.

Closing this to try tweaking Scaladoc where it decides which settings to apply, as mentioned above. (Rather than fiddling with ScalaSettings.)

To coin a phrase, "possibly not this evening," as `publishLocal` fails in Scaladoc, though it fails differently  for non-bootstrapped in tree unpickler.

2026-06-05 06:18 UTC, eejbyfeldt commented
@som-snytt Did you end up doing any more work on this?

My reading of the discussion was that we were fine with the change it self. But it was not merge because the compiler scaladoc had warnings that now became fatal? Could we just disable `-Werror` for the scaladoc part until those can be addressed separately?