Check only existing conflicting def with source
scala/scala3 pull request #17439
Opened 2023-05-09 07:29 UTC by som-snytt

2023-05-09 18:33 UTC, som-snytt commented
@lrytz I pushed a fix for when the inherited member is overloaded, so it's necessary to consult alternatives for source.

I see I was confused by overloaded `def Value` in `Enumeration`. The neg test is where the inherited overload is in the current file and we want to check that the conflicting definition is also in the current file.

I should have poured my second coffee before pushing.

2023-05-09 22:13 UTC, som-snytt commented
The fix exposes the overloaded `retry`. But that is not intended: it should check that both symbols are from the current compilation unit. It is weird but not wrong to mix in utility methods. I swear never again to say, Nobody codes like that.
```
 [error] -- [E049] Reference Error: /__w/dotty/dotty/community-build/community-projects/akka/akka-actor-tests/src/test/scala/akka/pattern/RetrySpec.scala:21:20 
[error] 21 |      val retried = retry(() => Future.successful(5), 5, 1 second)
[error]    |                    ^^^^^
[error]    |                    Reference to retry is ambiguous.
[error]    |                    It is both defined in package akka.pattern
[error]    |                    and inherited subsequently in class RetrySpec
```
Indeed,
```
package object pattern
    extends PipeToSupport
    with AskSupport
    with GracefulStopSupport
    with FutureTimeoutSupport
    with RetrySupport
```
and
```
class RetrySpec extends AkkaSpec with RetrySupport {
```
also just to cover all the bases
```
object RetrySupport extends RetrySupport
```

2023-05-10 03:33 UTC, som-snytt commented
I remember from days of C, walking past someone's open office door, the voice of an older coder patiently explaining to a young person why they can't have a global `int i` in the code. (This was a large project where every group had a name prefix which apparently was not mechanically enforced.)

```
[error] -- [E049] Reference Error: /__w/dotty/dotty/community-build/community-projects/specs2/core/shared/src/main/scala/specs2/run.scala:27:4 
[error] 27 |    run(args, exit = true)
[error]    |    ^^^
[error]    |    Reference to run is ambiguous.
[error]    |    It is both defined in package specs2
[error]    |    and inherited subsequently in object run
[error]    |
[error]    | longer explanation available when compiling with `-explain`
```
that is
```
object run extends ClassRunnerMain:
  def main(args: Array[String]) =
    run(args, exit = true)
```
where it inherits an overloaded `run` from `ClassRunnerMain`.

The advantage of naming the internal method `doRun` is that while coding, you will inevitably start singing, "Da do-run-run-run, da do-run-run."

2023-05-12 12:47 UTC, lrytz commented
I think the ambiguity error on
```
object run extends ClassRunnerMain:
  def main(args: Array[String]) =
    run(args, exit = true)
```
is not bad, this is the sort of thing that can confuse people.

2023-05-12 12:52 UTC, som-snytt commented
Oh my proposal was already merged https://github.com/etorreborre/specs2/pull/1153

2023-05-12 17:04 UTC, odersky requested changes
This currently fails for specs2, so it seems we need to improve the logic.

2023-05-12 21:17 UTC, som-snytt commented
@odersky I improved specs2 instead.

I think this is exactly the ambiguity that was intended originally. (See Lukas https://github.com/lampepfl/dotty/pull/17439#issuecomment-1545692646)

Or, perhaps you will say, This is why top-level things were excluded originally.

The specs2 example is where I would say, No one codes like that.

If the compiler doesn't help here, then there must be a lint for it. (I would accept that the ambiguity error should be reverted in favor of a 3rd-party lint.)

"I don't know what `run()` means in this context" is sad.

2023-05-16 18:30 UTC, lrytz commented
Yeah, same error here. Should I revert that commit on dotty-staging?

2023-05-16 18:42 UTC, som-snytt commented
@lrytz that was related to https://github.com/lampepfl/dotty/pull/17428

I mentioned the PR and that one could not tell if or when it might land. There is a request to improve debugging, but there is also the dotty PR to improve debugging inline code, which will touch line numbers.

2023-06-26 13:13 UTC, lrytz commented
Ready to review (@odersky). Short history
  - this fixes a corner-case of https://github.com/lampepfl/dotty/pull/17033
  - it was half approved ("otherwise LGTM" above)
  - specs2 needed a fix (https://github.com/etorreborre/specs2/pull/1153), not a bad example of how the new warning enforces cleaner code
  - the specs2 update was delayed for other reasons, but is now done
  - the original PR (17003) was reverted in the meantime https://github.com/lampepfl/dotty/pull/17438

So this PR reverts the revert, and adds the fix.

2023-07-05 11:41 UTC, lrytz commented
Added a forward-port of https://github.com/scala/bug/issues/12816 (package object members are not conflicting with inherited definitions).

2024-09-15 02:11 UTC, closed without merging