Deprecation of case class elements
scala/scala3 pull request #17911
Opened 2023-06-06 09:33 UTC by som-snytt

Fixes #17908

Also when message is empty, improve
```
-- Deprecation Warning: ------------------------------------------------------------------------------------------------
1 |f
  |^
  |method f is deprecated since :
val res0: Int = 42
```
to
```
-- Deprecation Warning: ------------------------------------------------------------------------------------------------
1 |f
  |^
  |method f is deprecated
val res0: Int = 42
```

2023-08-28 21:33 UTC, SethTisue commented
(removing Som's assignment to make it show up in the unassigned-PRs roundup)

2024-02-01 10:35 UTC, hamzaremmal commented
@som-snytt Can you fix the conflict and squash everything in a single commit ?

2024-02-01 12:59 UTC, hamzaremmal requested changes

2024-02-01 12:59 UTC, hamzaremmal commented on tests/pos/i11022.scala
I would also add a check file for this test and move it to the `warn` directory.

2024-02-01 12:59 UTC, hamzaremmal commented on tests/pos/i11022.scala
>  // scalac: -Werror -deprecation
```suggestion
//> using options  -deprecation
```

2024-03-19 23:11 UTC, som-snytt commented
It seems to be compensating for missing deprecation of case class `C.apply` and `unapply`.

The exclusion for case class is similar to the exclusion for enum, but restricted to synthetics.

2024-04-14 12:18 UTC, hamzaremmal approved these changes

2024-04-14 12:18 UTC, merged