Flag class file collision as error
scala/scala3 pull request #19332
Opened 2023-12-25 23:39 UTC by Friendseeker

Fixes #19248

2024-01-03 08:44 UTC, nicolasstucki approved these changes

2024-01-03 08:46 UTC, nicolasstucki requested changes
We need a test that reproduces this issue and checks that the error is emitted.

2024-10-10 06:57 UTC, Friendseeker commented
Nicolas's Github status says `On vacation`...

@smarter Would you like to take a really quick look at this PR? This PR is small and should be light to review.

2024-10-10 10:25 UTC, smarter approved these changes
LGTM, I was hit by this just recently!

2024-10-10 10:25 UTC, merged