Make aliases of `MatchAlias`es normal `TypeAlias`es
scala/scala3 pull request #19871
Opened 2024-03-04 16:25 UTC by EugeneFlesselle

Proposes to make `isMatch` true only for `MatchType`s and higher-kinded abstraction of them.

As a result, code using `isMatch` to choose between a `TypeAlias` and `MatchAlias` will now use a `TypeAlias` when aliasing a `MatchAlias`. Which in turn allows for better de-aliasing, since `dealias` only de-aliases standard type aliases.

`tryNormalize` on `AppliedType` should only attempt reduction if there is an underlying match type. This could previously be identified by a `MatchAlias` tycon. We now need a recursive check.

Fixes #19821

2024-03-05 14:59 UTC, dwijnand commented
Alternative to #19854

2024-03-07 22:46 UTC, dwijnand reviewed
Here's two more places where I wonder whether we need change too:

1. The `MatchAlias` type test in TypeOps.simplify
2. The `MatchAlias` case in MatchType.InDisguise

Should those be `if tp.isMatchAlias` and `case AliasingBounds(alias) if tp.isMatchAlias` too?

2024-03-11 12:25 UTC, EugeneFlesselle commented
@dwijnand For MatchType.InDisguise:
```scala 3
object InDisguise:
  def unapply(tp: AppliedType)(using Context): Option[MatchType] = tp match
    case AppliedType(tycon: TypeRef, args) => tycon.info match
      case MatchAlias(alias) => alias.applyIfParameterized(args) match
        case mt: MatchType => Some(mt)
        case _ => None
      case _ => None
    case _ => None
```
If I am not mistaken, the `applyIfParameterized` will only reduce a single application of a TypeRef tycon. So any cases that would match `case AliasingBounds(alias) if tp.isMatchAlias` which did not match `case MatchAlias(alias)` would then fail the second match in any case. So I think the cases matching `MatchType.InDisguise` remain the same with the changes.

I'm now wondering if you meant we might want to also accept these cases, independently of how they are affected by the aliasing changes ?

An equivalent change on main would then be
```scala 3
object InDisguise:
  def unapply(tp: AppliedType)(using Context): Option[MatchType] = tp match
    case AppliedType(tycon: TypeRef, args) => tycon.info match
      case MatchAlias(alias) => alias.applyIfParameterized(args) match
        case mt: MatchType => Some(mt)
         case MatchType.InDisguise(mt) => Some(mt)
        case _ => None
      case _ => None
    case _ => None
```
which doesn't seem to break anything.

Also, it looks like `MatchType.InDisguise` and `underlyingMatchType` would then be doing nearly the same thing, not the latter uses `superType` which also does an `applyIfParameterized`. Maybe we only need one ?

2024-03-11 12:36 UTC, EugeneFlesselle commented
For `TypeOps.simplify`, I agree it should be `if tp.isMatchAlias` instead.

2024-03-12 11:27 UTC, dwijnand commented
Next is double-checking that we'll still function appropriately when we unpickle pre-3.4 tasty.  I think it's dealt with the Unpickler change, right?

2024-03-12 18:23 UTC, EugeneFlesselle commented
test performance please

2024-03-21 19:25 UTC, mbovel commented
test performance please

2024-04-08 15:03 UTC, odersky requested changes

2024-04-08 18:27 UTC, EugeneFlesselle commented
Note that this PR is now based on #20077, because run into the same issue with `neg/i15183` when updating `def isAnchor`.

2024-04-08 20:52 UTC, odersky approved these changes

2024-04-08 20:52 UTC, merged