Reduce projections of type aliases with class type prefixes
scala/scala3 pull request #19931
Opened 2024-03-12 16:03 UTC by odersky

Projections P # X are types that we would like to avoid. If X is a class type, there's nothing we can do. If X is an abstract type, we use skolemization and rewrite to (x?: P).X. If X is an alias type we should simply dealias but this was not done before.

This caused an exponential blowup in #19892, where we constructed types of the form

   ZPartialServerEndpoint[R, A, B, I, E, O, -C] # EndpointType[A, I, E, T, R] ... # EndpointType[A, I, E, T, R]

When the were 5 or more such selections, sompile times blew up (33s for 5, timeout after 5 minutes for 6). I am still not qute sure where the blowup happened. Looking at stacktraces of random interrups it seemed to be in a deep recursion of memberDenot and asSeenFrom calls.I believe it would still be interesting to find out more about this, in case there are other similar situations where combinations of deep projections with wide applications cannot be avoided.

But for this precise problem, eagerly dealising fixes it.

2024-03-12 22:58 UTC, odersky commented
@rochala Can you help me fix the 2 presentation compiler test failures? I am not sure what to do here.

2024-03-12 23:00 UTC, rochala commented
I'll check it the first thing in the morning

2024-03-13 13:37 UTC, rochala commented
Dealiasing affects the typed trees which we are using for various features.
The tests that failed can be fixed by migrating to untyped trees, but there are other features such as hovers / go to type definition which can be more problematic, as the tree contains already dealiased type. 

I suppose it could be done if we analyse each select whether it is actually a type projection, and try recreating the original type by hand.

I will try to implement those workarounds unless you have a better idea.

2024-03-13 14:39 UTC, odersky commented
Does it just apply to # projections `A # X`? In that case I think we can also simply drop the behavior and the tests. Such projections are quite rare. For instance the dotty code base does not have a single occurrence of #. So I personally would not care at all what kind of hovers I get. And for others it would be a good indicator to change the design, since IME relying on # usually does not end well. 

I believe the _only_ reason to use A # B is if both `A` and `B` are classes and we want to model references to inner classes in the Java style. Otherwise, if you have to resort to it, it usually means your design is wrong. Maybe we should do a linter rule for that.

2024-03-13 15:20 UTC, rochala commented
> Does it just apply to # projections A # X?
It seems like this is the case.

This functionality was only tested in one suite, the one that failed, so I can say it wasn't truly supported by presentation compiler. This also impacts generated semanticdb output.

Feel free to add `@Ignore` for those tests. I'll create the ticket for this after this PR is merged so we don't lose a track of this. 
Other than that, I think the review of the solution should be done by someone more experienced.

2024-03-14 12:33 UTC, odersky commented
test performance please

2024-03-20 08:52 UTC, odersky commented
We should get benchmarks back before we can merge this. I want to rule out slowdowns in some scenarios.

2024-03-22 10:06 UTC, odersky commented
So performance seems to not worse and maybe a bit better. @smarter do you want to give this q quick review?

2024-03-26 13:55 UTC, smarter requested changes
Otherwise LGTM.

2024-03-26 14:18 UTC, odersky commented on compiler/src/dotty/tools/dotc/core/Types.scala
> +     *  these projections might arise, though.
Yes, but I am not sure we can dealias without breaking stuff here. It is a super low-level code.

2024-03-27 21:15 UTC, merged