Add support for `var` in refinements
scala/scala3 pull request #19982
Opened 2024-03-19 17:54 UTC by hamzaremmal

2024-03-23 16:36 UTC, odersky requested changes

2024-03-23 16:36 UTC, odersky commented on compiler/src/dotty/tools/dotc/ast/Desugar.scala
> +    val refinements1 = refinements.flatMap {
It's more efficient to make this a `refinements.mapConserve(...).flatten`. If there are no `var` refinements this would never copy the trees.

2024-03-23 16:36 UTC, odersky commented on compiler/src/dotty/tools/dotc/ast/Desugar.scala
> +            .withMods(Modifiers(tree.mods.flags & (AccessFlags | Synthetic), tree.mods.privateWithin))
This expression appears twice and could be lifted out. Also, one can use `withFlags`.
```scala
val mods1 = tree.mods.withFlags(tree.mods.flags & AccessFlags | Synthetic)
```

2024-03-23 16:36 UTC, odersky commented on compiler/src/dotty/tools/dotc/ast/Desugar.scala
> +        List(getter, setter)
If we go with `mapConserve`, this will be `Thicket(getter, setter)`

2024-03-23 16:36 UTC, odersky commented on compiler/src/dotty/tools/dotc/ast/Desugar.scala
> +      case tree => tree :: Nil
If we go with `mapConserve`, this will be `tree`.

2024-03-23 16:36 UTC, odersky commented on docs/_docs/internals/syntax.md
> +                    |  ‘var’ ValDcl
Same change needed in `reference/syntax.md`.

2024-04-03 14:06 UTC, odersky approved these changes

2024-04-03 14:07 UTC, Gedochao commented
This has been decided to be included in the 3.5.0 release.

2024-04-03 14:20 UTC, merged