Optimize main.js
scala/scala3 pull request #20093
Opened 2024-04-05 02:00 UTC by RedYetiDev

This Pull Request optimizes the functions used in `/docs/_spec/public/scripts/main.js`.

## Changes made:

1. `currentChapter()` function was simplified using `split()` and `pop()` instead of `lastIndexOf()` and `substring()`.
2. Used template literals for string interpolation.
3. Simplified the `heading` function by reducing repetitive code and improving readability.
4. Changed `.removeClass()` and `.addClass()` to `.toggleClass()` for toggling the class based on condition.
5. General cleanup and optimization for better readability and performance.

2024-04-05 02:24 UTC, SethTisue commented
why remove comments?

2024-04-05 10:24 UTC, RedYetiDev commented
> why remove comments?

My code prettier automatically removes them, I can add them back if you'd like?

2024-04-06 14:04 UTC, RedYetiDev commented
Sure, I'll add them back later today. I've also fixed my minifier settings, sorry.

2024-04-07 12:16 UTC, RedYetiDev commented
Comments have been added

2024-04-16 10:15 UTC, jchyb requested changes
Sorry for the long wait. The changes look good, I just have a few nitpicks.

2024-04-16 10:15 UTC, jchyb commented on docs/_spec/public/scripts/main.js
> +  const headerCounts = this.headerCounts;
Can we go back to using `this.headerCounts` directly (without assigning to const)? It reads a bit confusing here since we later modify its contents

2024-04-16 11:24 UTC, RedYetiDev commented
> Sorry for the long wait. The changes look good, I just have a few nitpicks.

No problem! Take your time!

2024-05-06 12:15 UTC, jchyb approved these changes
LGTM!

2024-05-06 12:16 UTC, merged