Widen unsafe reach capabilities instead of erroring
scala/scala3 pull request #20250
Opened 2024-04-23 13:05 UTC by Linyxus

Fixes #20204

2024-04-25 18:46 UTC, odersky commented
reaches.scala still has errors?

2024-05-19 16:24 UTC, odersky requested changes
Can we rearrange this PR into two commits:

 - One commit should contain all changes that we would want to revert when we change to existentials.
 - The other commit should contain tests and everything else that we want to keep.

2024-05-28 22:37 UTC, Linyxus commented
Rebasing is done!

2024-05-29 08:15 UTC, odersky approved these changes
The test failures still need fixing. Otherwise good to go in.

2025-05-20 14:45 UTC, Linyxus commented
superseded by latest developments of rcaps.

2025-05-20 14:45 UTC, closed without merging