When registering Ident use, consider the original span for synthetics
scala/scala3 pull request #20575
Opened 2024-06-15 18:31 UTC by natsukagami

---
name: "\U0001F527 Fix issue"
about: Open a new pull request for the Dotty Compiler that fixes an issue from the issue tracker
title: 'Fix #XYZ: A SHORT FIX DESCRIPTION'
assignees: ''

---

## Fix #19970

- Consider the original span for synthetics for registering Ident use
- Clarify that tryFindSynthetic is for `Apply | TypeApply` tree
- Update tests

2024-07-01 08:53 UTC, rochala commented
I looked at this, and I think it didn't solve the issue I've had, but the reason is completely on me. I made a mistake when I reported it. Likewise, I have updated the comment on the issue with the real reproduction. The fix should be similar, though.

2024-07-01 10:47 UTC, rochala requested changes
I think that the solution has to be a bit different.

Right now we're logging the occurence of local1, but we should instead go to the RHS of the ValDef from lifting. Then we should go over all calls and register their usage (they have correct spans).

Example:

```scala
object T:
  def enrichedCompilerCompletions() =
    val compilerCompletions: Seq[String] = ???

    compilerCompletions
      .toList
      .flatMap(toCompletionValues)
      .filterInteresting()


  def toCompletionValues(x: String): List[String] = ???

  extension (l: List[String])
    def filterInteresting(qualType: String = ""): List[String] = ???
``` 

results in:

```
Occurrences:
[3:7..3:8) <= _empty_/T.
[4:6..4:33) <= _empty_/T.enrichedCompilerCompletions().
[5:8..5:27) <= local0
[5:29..5:32) => scala/package.Seq#
[5:33..5:39) => scala/Predef.String#
[5:43..5:46) => scala/Predef.`???`().
[7:4..9:34) => local1
[10:7..10:24) => _empty_/T.filterInteresting().
[13:6..13:24) <= _empty_/T.toCompletionValues().
[13:25..13:26) <= _empty_/T.toCompletionValues().(x)
[13:28..13:34) => scala/Predef.String#
[13:37..13:41) => scala/package.List#
[13:42..13:48) => scala/Predef.String#
[13:52..13:55) => scala/Predef.`???`().
[15:13..15:14) <= _empty_/T.filterInteresting$default$2().(l)
[15:13..15:14) <= _empty_/T.filterInteresting().(l)
[15:16..15:20) => scala/package.List#
[15:21..15:27) => scala/Predef.String#
[16:8..16:25) <= _empty_/T.filterInteresting().
[16:26..16:34) <= _empty_/T.filterInteresting().(qualType)
[16:36..16:42) => scala/Predef.String#
[16:50..16:54) => scala/package.List#
[16:55..16:61) => scala/Predef.String#
[16:65..16:68) => scala/Predef.`???`().
```

But it should rather be:

```
Occurrences:
[3:7..3:8) <= _empty_/T.
[4:6..4:33) <= _empty_/T.enrichedCompilerCompletions().
[5:8..5:27) <= local0
[5:29..5:32) => scala/package.Seq#
[5:33..5:39) => scala/Predef.String#
[5:43..5:46) => scala/Predef.`???`().
[7:4..7:22) => local0
[8:6..8:12] => .toList
[9:6..9:xx] => .flatMap
[9:xx..9:yy] => toCompletionValue
[10:7..10:24) => _empty_/T.filterInteresting().
[13:6..13:24) <= _empty_/T.toCompletionValues().
[13:25..13:26) <= _empty_/T.toCompletionValues().(x)
[13:28..13:34) => scala/Predef.String#
[13:37..13:41) => scala/package.List#
[13:42..13:48) => scala/Predef.String#
[13:52..13:55) => scala/Predef.`???`().
[15:13..15:14) <= _empty_/T.filterInteresting$default$2().(l)
[15:13..15:14) <= _empty_/T.filterInteresting().(l)
[15:16..15:20) => scala/package.List#
[15:21..15:27) => scala/Predef.String#
[16:8..16:25) <= _empty_/T.filterInteresting().
[16:26..16:34) <= _empty_/T.filterInteresting().(qualType)
[16:36..16:42) => scala/Predef.String#
[16:50..16:54) => scala/package.List#
[16:55..16:61) => scala/Predef.String#
[16:65..16:68) => scala/Predef.`???`().
```

2024-07-01 10:50 UTC, tgodzik commented on tests/semanticdb/expect/NamedApplyBlock.expect.scala
> +  def recursive/*<-example::NamedApplyBlockMethods.recursive().*/ = foo/*->example::NamedApplyBlockMethods.foo().*//*->local1*/(local/*->example::NamedApplyBlockMethods.local.*/, c/*->example::NamedA
```suggestion
  def recursive/*<-example::NamedApplyBlockMethods.recursive().*/ = foo/*->example::NamedApplyBlockMethods.foo().*/(local/*->example::NamedApplyBlockMethods.local.*/, c/*->example::NamedApplyBlockMethods.foo().(c)*/ = foo/*->example::NamedApplyBlockMethods.foo().*/(local/*->example::NamedApplyBlockMethods.local.*/, c/*->example::NamedApplyBlockMethods.foo().(c)*/ = 3))
```
That local doesn't exist in the source code so we should not add it to occurrences

2024-10-29 15:19 UTC, natsukagami commented
Superceded by #21856

2024-10-29 15:19 UTC, closed without merging