In selector check, respect prefix and compare finalResultType to bound
scala/scala3 pull request #20894
Opened 2024-06-29 06:50 UTC by som-snytt

Fixes #19657 
Fixes #20860

2024-07-01 12:24 UTC, som-snytt commented
Further tweaks forthcoming.

2024-07-03 10:08 UTC, Gedochao commented
@som-snytt how much work do you think it still requires? 
It seems we might want to backport the fix for #20860  to 3.5.0 at the very least... 
do you need any help?

2024-07-03 10:15 UTC, sjrd requested changes
The first commit is a bit suspicious, and might be the cause of the CI failures.

The second commit looks good and might pass more easily if submitted as an independent PR.

2024-07-03 10:15 UTC, sjrd commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +    private val usedInScope = Stack(mut.Set.empty[(Symbol, Option[Name], Type, Boolean)])
This is suspicious. `Type`s don't have a meaningful `==` test in general. Why is it OK to use a `Type` in a `Set` here?

2024-07-03 10:15 UTC, sjrd commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +          else selData.qualTpe =:= prefix && (
Let's put this on a dedicated line ;)
```suggestion
          else
            selData.qualTpe =:= prefix && (
```

2024-07-03 10:15 UTC, sjrd commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +    final case class ImportSelectorData(val qualTpe: Type, val selector: ImportSelector):
This seems unnecessary.

2024-07-03 11:11 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +    final case class ImportSelectorData(val qualTpe: Type, val selector: ImportSelector):
sadly I needed string debug

2024-07-03 11:15 UTC, som-snytt commented
I'll submit commit 2 separately, as I was about to do except it's one line.

I'll follow up the fix for commit 1 after the American holiday.

2024-07-07 13:27 UTC, som-snytt commented
The previous test fails were because the new prefix check (in `isInImport`) doesn't apply when `isDerived` and also for top-level defs where the prefix becomes a package object (not sure if that `=:=` test should work, or if there's a convenient idiom, or if the check is even useful). The derived check uses dealiased types, not sure if a better mechanism is warranted.

I'll clean up and also look for improvements.

2024-10-02 19:37 UTC, som-snytt commented
Rebased and split out commits for easier review.

This includes adding the prefix type to `Usage`; simplifying gathering the warnings in `getUnused`, avoiding intermediate collections and extra sorting; mild refactors for readability.

This is the July commit and not the August rewrite, which fixes scope bugs by leveraging normal miniphase traversal and avoiding the special traverser; which allows putting `CheckUnused` in a single megaphase with `CheckShadowing`, so that is worth returning to. I'll do that if this PR of limited scope receives a review.

Example extra test fixed in August:
```
object Constants:
  val i = 42
class `scope of super`:
  import Constants.i // bad warn
  class C(x: Int):
    def y = x
  class D extends C(i):
    import Constants.* // does not resolve i in C(i)
    def m = i
```
As the comment reminds me, it incorrectly detects the superconstructor ref as resolved by the nested import.

Also note that the inner wildcard is not ambiguous because both imports resolve to the same symbol. But a further improvement would be to warn that the inner import is, if not unused, then spurious.

2024-10-06 21:02 UTC, som-snytt commented
Cherry-picked some old commits.

As a reminder to future self, the mega phase was broken because CheckShadowing sees the nested X as shadowing.
```
class F[X, M[N[X]]]
```
The fix [sic] is to ignore everything nested because it ignores constructor-owned X and M. [Previous attempt had been to short-circuit transformDeep so CheckShadowing doesn't see subtrees of "other" trees.]

The fix [also sic] to superclass context noted in previous comment is also novel: since all the "context" approximation is for the purpose of import tracking, it doesn't need to capture all the subtlety of a true super class constructor context (with class parameters in scope). Instead, just detect that a reference occurred in a parent tree, and then kick it upstairs in popScope.

The mechanism for tracking `derives` is entirely reworked.

The "inner traverser" is removed in favor of matching "other" trees and transforming their parts. I see there was some long discussion about this. 

The miniphase should be rewritten to leverage existing Context and Scope instead of custom structures. The problem of tracking just symbols is simpler (as in Scala 2), but for import tracking, it should use ImportContext etc. (The other PR for import tracking followed Scala 2 and let the compiler record lookups as they happen.) The motivation for proper contexts is so that a "lint framework" can rely on it, instead of custom traversals. For this phase, top-down may be more efficient than bubbling up references until they find a definition or import. Per context, a reference need be looked up only once, and then only if there are outstanding unused definitions or imports.

2024-10-06 21:07 UTC, som-snytt commented
`warn/unused-privates` has `NO warn` comments to revisit.

2024-10-09 06:12 UTC, som-snytt commented
> I'll follow up the fix for commit 1 after the American holiday.

That is Thanksgiving Day shortly after the national election, of course.

2024-11-05 16:36 UTC, som-snytt commented
I see I was in the middle of adding commits a month ago and did not implement the speculation from my previous comment.

My brain glazes over when I look at this PR. Also I have to re-read "getting started as a contributor" to understand "testing your changes". But I see this PR includes showing vulpix results more nicely.

2024-11-06 12:41 UTC, som-snytt commented
There are `pos` tests that check for "no warnings" using `-Werror` as in Scala 2 partest, but should be under `warn` which will check that is produces zero warnings.

2024-11-10 17:09 UTC, som-snytt commented
I didn't get around yet to handling constructor contexts when I worked around superconstructor contexts. https://github.com/scala/scala3/issues/21917

Note to self: don't neglect secondary constructors, which are lexically nested but typechecked like primary ctor in outer context.

2024-11-22 19:17 UTC, som-snytt commented
That link is a reminder to add `origin` to diagnostics.

2025-01-13 16:24 UTC, som-snytt commented
squashed because couldn't be bothered to rebase the conflict. I saved a branch in case.

Still need to fix the unpickle test failure. Then I will book the progress to avoid further conflicts. More accommodations are needed for compiletime.

2025-01-15 19:19 UTC, som-snytt commented
This breaks the unpickler test, or rather this is what unbreaks it:
```
--- a/compiler/src/dotty/tools/dotc/Compiler.scala
+++ b/compiler/src/dotty/tools/dotc/Compiler.scala
@@ -51,7 +51,7 @@ class Compiler {
     List(new Staging) ::            // Check staging levels and heal staged types
     List(new Splicing) ::           // Replace level 1 splices with holes
     List(new PickleQuotes) ::       // Turn quoted trees into explicit run-time data structures
-    List(CheckUnused.PostInlining()) ::  // Check for unused elements
+    List(new CheckUnused.PostInlining) ::  // Check for unused elements
     Nil
```
I don't have bandwidth to investigate why.

2025-01-15 21:31 UTC, som-snytt commented
@sjrd This is "ready for review."

`resolveUsage` is the logic for deciding whether a name was obtained from an import or definition. (That includes the fix in the PR title.)

It walks `Context` owners like a name look-up, but attempts some caching at certain contexts. That is for correctness and hopefully efficiency (but I haven't tested performance yet).

`RefInfos` contains the import, definitions, and references that are collected. It omits the stacks for scoping from the previous implementation.

It attempts to track nested `Inlined` call site positions: resolveUsage happens if the current tree is at a call pos, or if it looks like `summonInline` (by its span of zero extent). It also counts `inline def` to avoid warning there; a new option (to be done) will enable linting inline defs. This is similar to Scala 2, where macro expansions "consume" elements but don't introduce new warnings; but an option allows linting before or after expansion.

There are various tiresome mechanisms which are expected to just work without tweaking options.

Another principle is to minimize surface area with other components; this is restricted to a few attachments.

A few minor clean-ups remain, including ensuring that `compiletime` doesn't warn (because information is elided early). I speculated that it might be useful to run again after erasure. Avoiding false positives is a high priority, but also inline and compiletime (or let's just say language features) should have linting support. I haven't verified that lints are amenable to suppression; there are tickets for nowarn; but suppression is deemed a last resort.

There are 100 LOC for deleting unused imports which should be moved to a cupboard, as it is supplementary, to be brought out on special occasions; it's a port from Scala 2.

2025-01-16 14:11 UTC, sjrd requested changes

2025-01-16 16:35 UTC, som-snytt commented on library/src/scala/compiletime/package.scala
Thanks, I noticed it: I had touched then reverted the file but haven't fixed this permissions glitch yet. I'd like to figure out what lapse of gitfu caused it.

2025-01-16 19:22 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +      //println(s"OTHER ${tree.getClass} ${tree.show}")
putting them back under a line comment *was* the clean-up!

2025-01-16 19:46 UTC, som-snytt commented on tests/warn/i15503f.scala
> +      //case '{ ${Expr(opt)} : Some[T] } => Some(opt) // make Type param unused after typer
It's the same as the previous case, but the parameter `using Type` is unused, but does not warn under `-Wunused:implicits`. Now I'm not sure why. It's not named and `Type` has no declared members.

2025-01-16 19:52 UTC, som-snytt commented on tests/warn/i15503kb/power.scala
> +  import scala.concurrent.* // warn [taps mic]
Make sure it's warning. Inside these tests, if it's testing that elements do *not* warn, then you'd never know if warnings were turned off (for whatever feature). In retrospect, I'm leaning toward preferring a fixed corpus which is run under various settings: then all the code is tried under all the options, in some combination. (The fixed corpus need not be one huge file, but a test group.)

2025-01-16 19:56 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +      || imp.expr.tpe.member(sel.name.toTermName).hasAltWith(_.symbol.isCanEqual)
I'd also like to delete that whole thing: I don't think `strict no implicit warn` is useful if the check is working correctly (as it ought to be), and also I'm not sure `CanEqual` needs special treatment any more.

2025-01-16 19:57 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +    /** Is it the first import clause in a statement? `a.x` in `import a.x, b,{y, z}` */
!

2025-01-16 20:10 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +              val ok = clz.getConstructors.head.getParameters.map(p => termName(p.getName)).toList.init
Yes, I didn't want to read class files just for this "cheapy" attempt to get some param names for a warning. This is so `case Ident(name) =>` doesn't warn because `name` is the name. I'll look into improving it. The issue is the decoupling in the quotes api.

2025-01-16 20:44 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +  def absolveVariableBindings(ok: List[Name], args: List[Tree]): Unit =
Then the mathematicians must not say "absolute value" or the chemist "absolute alcohol" or the Swedish distiller "Absolut". The condition of absolution is to be freed from impairment, also in property rights. I feel more strongly about `Bind`, as this series of meanings relies on a primary binding from which one must be released (as from any obligation or duty, from which one may be absolved) in order to be fully realized. Excuse is just the dual of accuse. I'll go with "allow", allouer, laudare, which I didn't know is such a pleasant word, and with that end this lark or alouette.

2025-01-16 20:48 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +     || rhs.tpe =:= defn.NothingType
`compiletime.error`. If it produces no value, then the parameter is an input to nothing (though it could appear in an exception message, etc).

2025-01-16 21:03 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +    var inliners = 0 // depth of inline def
one is you saw an `Inlined`, the other is you saw `inline def`. For `Inlined`, avoid an inlined reference "resolving" an import (there was an existing test https://github.com/scala/scala3/blob/3.6.3/tests/warn/i15503a.scala#L71) and conversely in `inline def` an import might be resolved only after inlining a summonInline. There's a new ticket and test for that. However, all this is probably brittle and needs further work. I didn't want to exonerate or excuse or allow just everything. Or exonerate might be a good word, as the sense of exculpate is secondary. It means relieve as in relieve one's bladder or bowels.

2025-01-16 21:09 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +          defs.addOne((tree.symbol, tree.srcPos))
I intended to answer that question & will see what pops out here.

2025-01-16 21:12 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +    var precedence = Int.MaxValue // of current resolution; lower is higher
you shoot down my best turns of phrase. But it should be more symbolic than 1..4 so I'll improve that.

2025-01-16 21:18 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +      val qtpe = info.site //info.qualifier.tpe.nn
ah I see qualifier is empty for root imports, which are consulted now. The reason for drilling up into root imports is to cache a result (`Object`). (Though I suppose it could stop once it reached a root import with the same result.)

2025-01-16 21:21 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +            candidate = cur
defs in other source files are lower precedence than imports

2025-01-16 21:23 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +        done = true
I had already used one return & I'm sure tpolecat's ears were burning, but I will persevere and add another.

2025-01-16 21:29 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +      // resolve if inlined at the position of the call, or is zero extent summon
That is the normal case, the tree is not an inline expansion. But now I think most Scala 3 code is inlined. Also this reverse-engineering from the synthetic position was just an observation; I'm not sure this is robust.

2025-01-16 21:33 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +  // import x.y; x may be rewritten x.y, also import x.z as y
that is https://github.com/scala/scala3/blob/3.6.3/compiler/src/dotty/tools/dotc/typer/Typer.scala#L586 except the comment should say y is rewritten.

2025-01-16 21:38 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +      case AppliedType(_, args) => // if tycon.typeSymbol == defn.TypeTestClass
documentary? It has already checked for TypeTest.unapply, so the extractor should be a TypeTest[A, B], where the user wrote `case _: B`.

Some combination of redundant code and comments should help me remember later what I was working out, for some definition of "working memory".

2025-01-16 21:41 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +  def warnings(using Context): Array[MessageInfo] =
Yes, I'll undertake that in a separate commit. Probably just a method for each case (params, privates, imports etc). I'll also move the "rewrite" logic out of the way. I did verify that the rewrite correctly edits the imports in the repo.

2025-01-17 02:40 UTC, som-snytt commented on tests/warn/i15503f.scala
> +      //case '{ ${Expr(opt)} : Some[T] } => Some(opt) // make Type param unused after typer
Apparently something to do with quote pickling, not printed by -Vprint. Is there a tool for showing trees that I don't know about? How can I reason about data structures that are invisible?

2025-01-17 02:45 UTC, som-snytt commented on tests/warn/i15503kb/power.scala
> +  import scala.concurrent.* // warn [taps mic]
I've begun (recently) to add `-Werror` in tests/warn to signal that no warnings are expected. That assists clarity. If there is a warning, though, you don't get a nice vulpix explanation.

2025-01-17 16:53 UTC, som-snytt commented on tests/warn/i15503f.scala
> +      //case '{ ${Expr(opt)} : Some[T] } => Some(opt) // make Type param unused after typer
To follow up, the TODO was that I wanted to show the implicit arg unused, but didn't know enough about quoting to do it; in addition, I lacked tooling just to show me the `Ident` tree in question.

2025-01-17 22:57 UTC, som-snytt commented
@sjrd I appreciate the review. I have addressed the tweaks and also a first refactor of the `warnings` loop, and also a refactor of `resolveUsage`.

The cache logic was flawed: now it caches the `Precedence` of the result. Otherwise, a subsequent look-up may have a more deeply nested result and doesn't know whether to keep it. (Contexts are ordered but don't bear nesting levels, so the highest precedence candidate wins.)

I will add commits for further accommodation of `compiletime` and `inline`, but do not plan to squash.

You may wish to wait for more tests, or review at your leisure. I'll ping you again if I've exhausted my resources.

2025-01-18 00:22 UTC, som-snytt commented
I commented that `-Werror` spoils the output of `tests/warn`, but that is not true (at least, as of now):
```
Compilation failed for: tests/warn/i21805.scala
-> following the diagnostics:
 at 0: No warnings can be incurred under -Werror (or -Xfatal-warnings)
 at 7: unused import
```

2025-01-21 00:11 UTC, som-snytt commented
@sjrd that is probably my limit for this PR

2025-01-28 09:29 UTC, sjrd commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +  def warnings(using Context): Array[MessageInfo] =
This is much better now. Thank you.

2025-01-28 09:30 UTC, sjrd approved these changes
Looks great! Thanks a lot for reworking that area which definitely deserved more attention.

Do you want to keep the commits as is or squash some of them? In any case, LGTM.

2025-01-28 15:37 UTC, som-snytt commented
Squashed, fixed conflict in posttyper (!), amended the comment, left the change for `import chaining` as a separate commit for visibility (it's just a tweak but not fully vetted).

I'll expect to follow up, for bugs or known false positives with compiletime ops.

2025-01-28 16:26 UTC, sjrd commented
There are some test failures in the CI. Can you take a look?

2025-01-28 19:29 UTC, merged

2025-03-20 18:15 UTC, 987Nabil commented
Can this be back ported to 3.3.x?

2025-03-21 09:00 UTC, tgodzik commented
We'll try to backport it for sure, though this might be quite difficult due to amount of changes. But the plan is to do it.