Tweak tparam unification to work with lambda cleanup
scala/scala3 pull request #22031
Opened 2024-11-26 14:51 UTC by dwijnand

Fixes #21981

2024-12-18 10:29 UTC, odersky reviewed
It looks reasonable to me. @smarter WDYT? You wrote the original code.

2025-01-08 23:29 UTC, smarter requested changes
I can reproduce the problem with the change in this PR if I change the receiver of `map2` to be a tuple of type parameters `(K1, K2)` instead of a single parameter `K`:
```scala
trait Ops[F[_], A]:
  def map0[B](f0: A => B): F[B] = ???

trait Functor1[G[_]]

trait Functor2[H[_]]:
  extension [C1, C2](hc: H[(C1, C2)])
    def map2[D](f1: (C1, C2) => D): H[D]

trait Ref[I[_], +E]

final class Cov[+F]

class Test:
  given [J[_]](using J: Functor1[J]): Functor2[J] with
    extension [K1, K2](jk: J[(K1, K2)])
      def map2[L](f2: (K1, K2) => L): J[L] = ???

  def t1[
    M[_[t]],
    N[_],
  ](using N: Functor1[N]): Unit =

    val x3: Ops[N, M[[t] =>> Ref[N, t]]] = ???

    val x2: N[(M[N], M[[t] =>> Ref[N, t]])] = x3
      .map0 { refs             => (???, refs) }
      .map2 { case (not, refs) => (???, refs) }
```
The root cause of the regression is that the removal of type variables in https://github.com/scala/scala3/pull/21466/files#diff-73257963d8a6d79cd4878ae4ff164e33c36629f77821886ffc7cea2e2e38af39R78 does not check that the removed type variables are not in use somewhere. I spent some time looking into it but couldn't find a robust way to do so (maybe a version of Inferencing#interpolateTypeVars that doesn't require a tree argument could be used on `pt` in `normalizedCompatible` to do this clean-up?), so I think for now it'd be best to just revert https://github.com/scala/scala3/pull/21466/

2025-02-19 16:09 UTC, smarter commented on compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala
>                        tvar.instantiate(fromBelow = false)
To clarify what I meant in my previous comment, the code after this commit is:
```scala
if belowOK then
  tvar.instantiate(fromBelow = true)
else if aboveOK then
  tvar.instantiate(fromBelow = false)
```
but if I swap the order of the branches:
```scala
if aboveOK then
  tvar.instantiate(fromBelow = false)
else if belowOK then
  tvar.instantiate(fromBelow = true)
```
then tests/pos/i21981.scala starts failing, so that must mean that aboveOK being true is not a good enough condition to ensure that instantiating a type variable is safe.

2025-02-20 19:26 UTC, smarter commented on compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala
> +                    // the tvars for B and K unified, instantiating `B := K`,
The check `tvar1.instanceOpt == tvar` accounts for that, but it doesn't account for `B := Foo[K]`. Here's a test case with `B := Contra[K]`:
```scala
case class Inv[T](x: T)
class Contra[-ContraParam](x: ContraParam)

trait Ops[F[_], A]:
  def map0[B](f0: A => Contra[B]): F[B] = ???

trait Functor1[G[_]]

trait Functor2[H[_]]

trait Ref[I[_], +E]

class Test:
  given [J[_]](using J: Functor1[J]): Functor2[J] with
    extension [K](jk: J[Contra[K]])
      def map2[L](f2: K => L): J[L] = ???

  def t1[
    M[_[t]],
    N[_],
  ](using N: Functor1[N]): Unit =

    val x3: Ops[N, M[[t] =>> Ref[N, t]]] = ???

    val x2: N[(M[N], M[[t] =>> Ref[N, t]])] = x3
      .map0 { refs             => Contra[Contra[(Nothing, M[[t] =>> Ref[N, t]])]](???) }
      .map2 { case (not, refs) => (???, refs) }
```

Now this could probably be fixed by checking `tvar.occursIn(tvar1.instanceOpt)` but at this point I'd started getting worried about time complexity: we're already inside two loops over all type variables and now we're traversing a type (in fact this is the traversal that `dependsOn` avoids for uninstantiated type variables).

2025-02-21 08:44 UTC, dwijnand commented on compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala
> +                      isInst ||= !excluded.contains(tvar1) && tvar1.instanceOpt == tvar
True, the instanceOpt check also subsumes the exclusion condition.

2025-02-24 10:42 UTC, dwijnand commented
> Now this could probably be fixed by checking `tvar.occursIn(tvar1.instanceOpt)` but at this point I'd started getting worried about time complexity: we're already inside two nested loops over all type variables and now we're traversing a type (in fact this is the traversal that `dependsOn` avoids for uninstantiated type variables).

Thanks for all the review @smarter, it's been great feedback.

Do you have another idea how we can deal with the original issue (the extra lambda polluting the constraint) if we revert #21466?

2025-02-26 23:56 UTC, smarter commented
> Do you have another idea how we can deal with the original issue (the extra lambda polluting the constraint) 

In `Inferencing.interpolateTypeVars`, we look for type variables among `tp` and `pt` using `Inferencing.variances`: https://github.com/scala/scala3/blob/399d008a6026ea18207f41397b083942497d4438/compiler/src/dotty/tools/dotc/typer/Inferencing.scala#L674 and variables which appear non-variantly are left uninstantiated (except if we can rely on their level to ensure instantiating them won't affect anything else in the constraint, cf https://github.com/scala/scala3/blob/399d008a6026ea18207f41397b083942497d4438/compiler/src/dotty/tools/dotc/typer/Inferencing.scala#L723-L729).

In tests/pos/i21981.scala if I call `Inferencing.variances(tp, pt)`, then `K` doesn't get picked up, but I change the definition of `variances` to not skip part of `pt`:
```diff
diff --git compiler/src/dotty/tools/dotc/typer/Inferencing.scala compiler/src/dotty/tools/dotc/typer/Inferencing.scala
index 2ebcd96d5bd..96634cdb1ac 100644
--- compiler/src/dotty/tools/dotc/typer/Inferencing.scala
+++ compiler/src/dotty/tools/dotc/typer/Inferencing.scala
@@ -586,7 +586,7 @@ object Inferencing {
       if (vmap1 eq vmap) vmap else propagate(vmap1)
     }

-    propagate(accu(accu(VarianceMap.empty, tp), pt.finalResultType))
+    propagate(accu(accu(VarianceMap.empty, tp), pt))
   }

   /** Run the transformation after dealiasing but return the original type if it was a no-op. */
```
Then we do get `K` appearing non-variantly, which should be enough to prevent us from instantiating (ideally, we should refactor `interpolateTypeVars` to be callable without a tree instead of replicating part of its logic elsewhere).

I don't think I had a good reason for using `pt.finalResultType` here in `variances`, but I haven't tried to see what happens if we do get rid of it.

2025-02-28 15:25 UTC, dwijnand commented
> I don't think I had a good reason for using `pt.finalResultType` here in `variances`, but I haven't tried to see what happens if we do get rid of it.

Thanks for the suggestion.  It looks like it works... until I encountered `tests/pos-custom-args/captures/i16116.scala`.  In the code:

```scala
val fr = cpsAsync[Future] {
   val y = asyncPlus(1,Future successful 2).asInstanceOf[Int]
   y+1
}
```

We end up looking for the implicit `CpsMonad[Future]` that `cpsAsync` needs, but if weconsume all of `pt` we end up type-checking that a `CpsTransform[Future]` is needed, before `makeContextualFunction` gets a chance to introduce it into the context...

2025-03-03 11:49 UTC, closed without merging