Remove special overriding logic for explicit nulls
scala/scala3 pull request #22243
Opened 2024-12-19 05:15 UTC by HarrisL2

Fixes #22071

2024-12-19 15:07 UTC, olhotak commented
The changes LGTM, but we'll need to get the CI running first.

There we see:
```
object creation impossible, since def compareTo(x$0: T | Null): Int in trait Comparable in package java.lang is not defined
```

The type of `x` should become a flexible type, not `T | Null`. So the question is why doesn't it become a flexible type.

2025-01-07 12:33 UTC, noti0na1 requested changes
Just a question about the ctx for `matches`. Otherwise LGTM

2025-01-07 12:33 UTC, noti0na1 commented on compiler/src/dotty/tools/dotc/core/Types.scala
> -      TypeComparer.matchesType(this, that, relaxed = !ctx.phase.erasedTypes)(using overrideCtx)
Do we still need to remove the `SafeNull` mode?

2025-01-07 15:34 UTC, HarrisL2 commented on compiler/src/dotty/tools/dotc/core/Types.scala
> -      TypeComparer.matchesType(this, that, relaxed = !ctx.phase.erasedTypes)(using overrideCtx)
Yes, I believe the comment above explains why. (and it also doesn't pass the tests without it)

2025-01-21 14:39 UTC, noti0na1 approved these changes

2025-01-21 14:40 UTC, merged